### ISSUE TITLE
[Question] could i translate contents to korean?

### ISSUE THREAD

**Issue by JaeYeopHan** [viraptor/reverse-interview#14]
Hi, I'm web engineer Jbee.

i am organizing interview question repository in korea (https://github.com/JaeYeopHan/Interview_Question_for_Beginner)

so... i want to add this contents to my repository with translation.
(Of course, i remain your repository link in my repo!!)

could i?

**Comment by matthiasgoergens** [comment]
https://github.com/viraptor/reverse-interview/blob/master/LICENSE suggests you can do that and outlines the legal conditions.  (Note: I am NOT the author.)

**Comment by JaeYeopHan** [comment]
@matthiasgoergens oh thanks!
I checked MIT license, but I wanted to check to the author! Thanks for the reply!

**Comment by viraptor** [comment]
Go ahead :) That would be great!

**Comment by JaeYeopHan** [comment]
thanks! (i add some emoji :))
here: https://github.com/JaeYeopHan/Interview_Question_for_Beginner/blob/master/Reverse_Interview/README.md

**Comment by viraptor** [comment]
And linked https://github.com/viraptor/reverse-interview/commit/4f069d57859b9dded5bfcaaefc77202ae56e8260
