### ISSUE TITLE
Suggestion: Climate Change Question

### ISSUE THREAD

**Issue by jay-pee** [viraptor/reverse-interview#20]
For me the issue of climate change is very important for the job decision!

Question Suggestion:
**What does the company do to fulfill its social responsibility for the fight against climate change?**

Maybe it is a little to passiv aggressiv when the company doesn't do anything about it. 

Please suggest other formulation, so we can discuss them. Maybe also more specific question could be derived from that. For example: Is the company using renewable energy as electricity source?

Would be great to add this kind of question to the list :)

**Comment by jensenak** [comment]
I fully support the effort to reduce climate change. I don't feel like a question on this topic belongs on this list.

Questions about company climate change, humanitarian, educational, and other such efforts are valid questions that individual candidates may choose to ask. This list seems to be centered directly on developing clear expectations about the job, team, compensation, and workload. I feel the requested question is out of scope here.

**Comment by jay-pee** [comment]
Thank you for your answer :) 

I thought this questions are about making clear if this workplace/position is a viable option to take. I can understand if people have other values/criteria for picking a job.

I have no problems when a company has made a informed decision of not taking actions against climate change. But in my opinion every company should have discussed at least if they want to take action. Therefore, I still think the question should be allowed, however not so aggressiv. 

Other suggestion:
**Does the company have a stance regarding climate change?**

**Comment by nitink4472** [comment]
Can i create a PR regarding questions on climate change?

**Comment by viraptor** [comment]
I'm torn on the initial question, but not for the reasons above.
Companies will usually publish and be proud of the actions they're doing for climate change, so I see the outcome as either:

- acknowledging you haven't looked for answers yourself first
- pointing out they're not involved

I like the second one better. It allows talking about future issues/projects.
Not one I'd ask, but it's not just my list :) Happy to include it.
