### ISSUE TITLE
[Improvement] contribution guidelines

### ISSUE THREAD

**Issue by yurireeis** [viraptor/reverse-interview#68]
Hey @viraptor , How are you doing?

I hope well.

So, this issue aims to set a contribution guideline at your project. As it grows, it's good to know How We Could have better chances to have a PR approved, and to follow your guidelines.

I felt free to open a PR with some standards (based on Contributor Covenant) as a kickstart.

Have a nice day!

related: https://github.com/viraptor/reverse-interview/pull/67

**Comment by viraptor** [comment]
Hi, thanks for the suggestion. Please see the comment on https://github.com/viraptor/reverse-interview/pull/67#issuecomment-590018170
I don't think I want to deal with non-specific contribution guides for now.
