### ISSUE TITLE
Plot 4D with different 4 variables (Create Carpet plots)

### ISSUE THREAD

**Issue by scitech2020** [viraptor/reverse-interview#81]
I am new to MatLab, and programming in general,.. 
I have 4 independent variables , x value corresponds to every value of [y,z,b].
how can I represent it in carpet plot however, I can not understand most of the carpet classes  available.. Is it like functions ??
Maybe with a surface, but I need to have same the 4 axis values written on the curves

close all
clear all
clc
x=[0 .3 .7 1.0];
y=[5 20 35 40];
zz=[0 .3 .6 .8];
b=[1 .5 .8 1];
[xx,yy]=meshgrid(x,zz)
[zz2,bb]=meshgrid(y,b)
surf(xx,yy,zz2,bb)

**Comment by viraptor** [comment]
This is definitely not the repo you want.

**Comment by viraptor** [comment]
Try stackoverflow.com instead

**Comment by scitech2020** [comment]
Thanks for your comment, but it was reported here several packages to obtain that, but I do not understand them ?

thanks,
