### ISSUE TITLE
Looking for Candidates - Recruitment / Germany

### ISSUE THREAD

**Issue by DidemOezer** [viraptor/reverse-interview#88]
Hi Guys, 

I appreciate your work here and I´m impresses by the written codes. I´m working as a specialised Recruitment Consultant with focus on AWS, DevOps and Cloud. So everybody with Knowledge in Kubernetes, Jenkins, Git, Cloud Computing, Docker etc. is more than welcome to contact me! 

There are some companies which evolved through this struggeling times of Covid19 and are actively looking for IT professionals to continue growing together. Do you want to be part of it? 

Cotact me: 
LinkedIn: https://www.linkedin.com/in/didem-%C3%B6zer-388253147/
E-Mail: d.oezer@jeffersonfrank.com

**Comment by viraptor** [comment]
This is not the place, stop spamming.
